SELECT  SALES_ITEM_NUMBER, SALES_NUMBER, ITEM_ID_OLD, ITEM_CODE_OLD, ITEM_CODE, ITEM_NAME, 
        ITEM_TYPE, ITEM_MODEL, ITEM_CATEGORY, ITEM_DEPARTEMENT, ITEM_DIVISION, ITEM_GROUP, 
        DESCRIPTION, BRAND, UNIT_PRICE_BEFORE_TAX, UNIT_PRICE_AFTER_TAX, QTY, PARENT_QTY, 
        SALE_PRICE, TOTAL_PRICE_AFTER_TAX, TOTAL_PRICE_BEFORE_TAX, TAX_PERCENTAGE, TAX_AMOUNT, 
        TOTAL_DISCOUNT_PERCENTAGE, TOTAL_DISCOUNT, DISCOUNT_COST_ON_PO, UNIT_COST, FINAL_COST, 
        UNIT_PROFIT, TOTAL_PROFIT, CUSTOMER_NAME, MEMBER_TYPE, CHANNEL_TYPE, SALES_DATE, SALES_TIME, 
        STORE_LOCATION, SALES_ITEM_REMARK, SALES_PERSON, SALES_STATUS, BARCODE, UOM, APPLIED_PROMO, 
        PROMOTION_TYPE, VOUCHER_NUMBER, PRINSIPAL, FULL_NAME_PRODUCT, ITEM_ADDITIONAL_INFO, ACTIVE_SKU, 
        ITEM_SMI, PARETO_TYPE, target, CLIENT_ID, CLIENT_NAME, CLIENT_GENDER, CLIENT_DOB, 
        CLIENT_CREATION_DATE, CLIENT_STORE_REGISTRATION, 
        TOTAL_NET_MARGIN_ACCURATE, TOTAL_GROSS_MARGIN_ACCURATE, MCH, FAST_MOVING, CATEGORY_CM, PIC_CM, 
        CAMPAIGN_NAME, NON_FUNCTIONAL_25, REBATE, REBATE_ERROR, `TIMESTAMP` 
FROM xilnex_rpt.tr_tbl_sales_by_item
WHERE SALES_DATE > '20231201'
AND PROMOTION_TYPE = 'Omega';


